# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[âœ](bold #36f9f6)' # Neon Cyan
error_symbol = '[âœ—](bold #ff7edb)'   # Neon Pink
vimcmd_symbol = '[V](bold #72f1b8)'  # Neon Green

[directory]
style = "bold #36f9f6"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ğŸ”’"

[git_branch]
style = "bold #fede5d" # Neon Yellow
symbol = "ï˜ "

[git_status]
style = "bold #ff7edb" # Neon Pink
conflicted = "ğŸ³"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
modified = "ğŸ“"
staged = '[++($count)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[nodejs]
symbol = "îœ˜ "
style = "bold #72f1b8"

[python]
symbol = "ğŸ "
style = "bold #fede5d"

[rust]
symbol = "ğŸ¦€ "
style = "bold #ff7edb"

[golang]
symbol = "ğŸ¹ "
style = "bold #36f9f6"

[crystal]
symbol = "ğŸ”® "
style = "bold #ff7edb"

[scala]
symbol = "ğŸµ "
style = "bold #fede5d"

[kotlin]
symbol = "ğŸ…º "
style = "bold #72f1b8"

[zig]
symbol = "âš¡ "
style = "bold #fede5d"

[lua]
symbol = "ğŸŒ™ "
style = "bold #36f9f6"

[dart]
symbol = "ğŸ¯ "
style = "bold #36f9f6"

[julia]
symbol = "à®ƒ "
style = "bold #72f1b8"

[cmake]
symbol = "â–³ "
style = "bold #fede5d"

[gradle]
symbol = "ğŸ˜ "
style = "bold #36f9f6"

[maven]
symbol = "ğŸ€ "
style = "bold #ff7edb"

[docker_context]
symbol = "ïŒˆ "
style = "bold #36f9f6"

[aws]
symbol = "â˜ï¸  "
style = "bold #fede5d"
disabled = false

[kubernetes]
symbol = "â˜¸ "
style = "bold #36f9f6"
disabled = false

[os]
disabled = false
style = "bold #fede5d"

[os.symbols]
Debian = "ïŒ† "
Ubuntu = "ïŒ› "
Macos = "ï…¹ "
Windows = "ï…º "

[package]
symbol = "ğŸ“¦ "
style = "bold #ff7edb"
disabled = false

[memory_usage]
disabled = false
threshold = 75
symbol = "ğŸ§  "
style = "bold #ff5555"
format = "$symbol[${ram}( | ${swap})]($style) "

[battery]
disabled = false
full_symbol = "ğŸ”‹ "
charging_symbol = "âš¡ "
discharging_symbol = "ğŸ’€ "

[[battery.display]]
threshold = 30
style = "bold #ff5555"

[container]
symbol = "ğŸ³ "
style = "bold #36f9f6"
disabled = false

[cmd_duration]
min_time = 500
style = "bold #fede5d"
format = "took [$duration]($style)"

[jobs]
symbol = "âœ¦ "
style = "bold #72f1b8"

[time]
disabled = false
style = "bold #ff7edb"
format = "at [$time]($style) "
