# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

# Inserts a blank line between shell prompts
add_newline = true

[character]
success_symbol = '[âœ](bold #36f9f6)' # Cyan
error_symbol = '[âœ—](bold #ff7edb)'   # Pink

[directory]
style = "bold #36f9f6"
truncation_length = 3
truncation_symbol = "â€¦/"

[git_branch]
style = "bold #fede5d" # Yellow
symbol = "ï˜ "

[git_status]
style = "bold #ff7edb" # Pink

[nodejs]
symbol = "îœ˜ "
style = "bold #72f1b8" # Green

[python]
symbol = "ğŸ "
style = "bold #fede5d"

[docker_context]
symbol = "ïŒˆ "
style = "bold #36f9f6"

[cmd_duration]
min_time = 500
style = "bold #fede5d"
