# Get editor completions based on the config schema
"$schema" = 'https://starship.rs/config-schema.json'

add_newline = true

[character]
success_symbol = '[âœ](bold #36f9f6)' # Neon Cyan
error_symbol = '[âœ—](bold #ff7edb)'   # Neon Pink
vimcmd_symbol = '[V](bold #72f1b8)'  # Neon Green

[directory]
style = "bold #36f9f6"
truncation_length = 3
truncation_symbol = "â€¦/"
read_only = " ğŸ”’"

[git_branch]
style = "bold #fede5d" # Neon Yellow
symbol = "ï˜ "

[git_status]
style = "bold #ff7edb" # Neon Pink
conflicted = "ğŸ³"
up_to_date = "âœ“"
untracked = "ğŸ¤·"
modified = "ğŸ“"
staged = '[++($count)](green)'
renamed = "ğŸ‘…"
deleted = "ğŸ—‘"

[nodejs]
symbol = "îœ˜ "
style = "bold #72f1b8"

[python]
symbol = "ğŸ "
style = "bold #fede5d"

[rust]
symbol = "ğŸ¦€ "
style = "bold #ff7edb"

[golang]
symbol = "ğŸ¹ "
style = "bold #36f9f6"

[docker_context]
symbol = "ïŒˆ "
style = "bold #36f9f6"

[aws]
symbol = "â˜ï¸  "
style = "bold #fede5d"
disabled = false

[kubernetes]
symbol = "â˜¸ "
style = "bold #36f9f6"
disabled = false

[cmd_duration]
min_time = 500
style = "bold #fede5d"
format = "took [$duration]($style)"

[jobs]
symbol = "âœ¦ "
style = "bold #72f1b8"

[time]
disabled = false
style = "bold #ff7edb"
format = "at [$time]($style) "
