# Yazi Theme (Synthwave '84)

[manager]
cwd = { fg = "#36f9f6" }

# Hovered
hovered         = { reversed = true }
preview_hovered = { underline = true }

# Find
find_keyword  = { fg = "yellow", italic = true }
find_position = { fg = "magenta", bg = "reset", italic = true }

# Marker
marker_selected = { fg = "#50fa7b", bg = "#50fa7b" }
marker_copied   = { fg = "#f1fa8c", bg = "#f1fa8c" }
marker_cut      = { fg = "#ff5555", bg = "#ff5555" }

# Tab
tab_active   = { fg = "#282a36", bg = "#bd93f9" }
tab_inactive = { fg = "#f8f8f2", bg = "#44475a" }
tab_width    = 1

# Border
border_symbol = "│"
border_style  = { fg = "#6272a4" }

[status]
separator_open  = ""
separator_close = ""
separator_style = { fg = "#44475a", bg = "#44475a" }

# Mode
mode_normal = { fg = "#282a36", bg = "#bd93f9", bold = true }
mode_select = { fg = "#282a36", bg = "#50fa7b", bold = true }
mode_unset  = { fg = "#282a36", bg = "#ff5555", bold = true }

# Progress
progress_label  = { fg = "#f8f8f2", bold = true }
progress_normal = { fg = "#bd93f9", bg = "#44475a" }
progress_error  = { fg = "#ff5555", bg = "#44475a" }

# Permissions
permissions_t = { fg = "#bd93f9" }
permissions_r = { fg = "#f1fa8c" }
permissions_w = { fg = "#ff5555" }
permissions_x = { fg = "#50fa7b" }
permissions_s = { fg = "#8be9fd" }

[input]
border   = { fg = "#bd93f9" }
title    = {}
value    = {}
selected = { reversed = true }

[select]
border   = { fg = "#bd93f9" }
active   = { fg = "#ff79c6" }
inactive = {}

[tasks]
border  = { fg = "#bd93f9" }
title   = {}
hovered = { underline = true }

[which]
mask            = { bg = "#44475a" }
cand            = { fg = "#36f9f6" }
rest            = { fg = "#6272a4" }
desc            = { fg = "#ff79c6" }
separator       = "  "
separator_style = { fg = "#44475a" }

[notify]
title_info  = { fg = "#50fa7b" }
title_warn  = { fg = "#f1fa8c" }
title_error = { fg = "#ff5555" }

icon_info  = ""
icon_warn  = ""
icon_error = ""
